### PR TITLE
Fix error when using setTimeout in service: sandbox is undefined

### PR DESCRIPTION
**Pull request by zhangmx**
Remove the line of sandbox.clearTimeout(timerId); in src/smxstate-node.js and add some tests for this change. Before removing the line , the tests could not pass.

### CODE REVIEW

**Comment by sonntam** [comment]
@zhangmx Thank you for  the contribution! Your TCP client implementation including the test is well done.

By just looking at the code however I could not quite comprehend what the problem with the `clearTimeout()` is. Can you give me a leg up and describe why the change is necessary just so I can understand?

Before creating a new version at npm.js I'll have to dive into the package upgrades as there seem to be some breaking changes with the new versions and I first have to know what this means for compatibility e.g. towards node-red 2.x. This might make it necessary to update the major version of this package. Please give me some time. 

Also the new xstate 5.0 is around the corner...

**Comment by zhangmx** [comment]
The `clearTimeout()` function call is fine, but the `sandbox` variable is undefined. I changed the code again, added the `sandbox` variable, and assigned the return value of `getSandbox(node)` to the `sandbox`, all tests passed.


> @zhangmx Thank you for the contribution! Your TCP client implementation including the test is well done.
> 
> By just looking at the code however I could not quite comprehend what the problem with the `clearTimeout()` is. Can you give me a leg up and describe why the change is necessary just so I can understand?
> 
> Before creating a new version at npm.js I'll have to dive into the package upgrades as there seem to be some breaking changes with the new versions and I first have to know what this means for compatibility e.g. towards node-red 2.x. This might make it necessary to update the major version of this package. Please give me some time.
> 
> Also the new xstate 5.0 is around the corner...

**Comment by zhangmx** [comment]
I'm learning xstate, maybe this setTimeout can be replaced by xstate's Delayed transitions? I am trying and experiencing xstate

**Comment by sonntam** [comment]
Thanks, I'll do some testing and code review. Unfortunately, I currently can't.

**Comment by sonntam** [comment]
@zhangmx I could reproduce and understand the problem. Thank you! Rather than merge your pull request I'd like to create a proper fix to just address the issue without incorporating your tcp example first.

The sandbox code was copied from node-red's core function node and I seem to have made an error with the reference to the `sandbox` variable. I was able to fix it by introducing a local reference variable for `sandbox`.

For me it worked without updating dependencies. But for now I changed the dependencies to use the latest minor version within the current major version to have some vulnerability fixes included. I had no problems this way during my tests. 

I'd also like to cherry-pick your commits for the vs code mocha explorer as well as the search exclude rules.

**Comment by sonntam** [comment]
I published version 1.3.0. Your example seems to run fine with it from what I can tell.

**Comment by zhangmx** [comment]
> I published version 1.3.0. Your example seems to run fine with it from what I can tell.

Thank you!

I am not very familiar with xstate and tcp, and I don't quite understand how to initiate tcp requests in xstate nodes and callback to update xstate status. Previously, I saw some examples in [https://stately.ai/registry/discover?page=1&facetFilters=%5B%5D&numericFilters=%5B%5D](https://stately.ai/registry/discover?page=1&facetFilters=%5B%5D&numericFilters=%5B%5D), but they do not belong to my current business scenarios and are too complex. 

Should tcp requests be in the code of xstate node's action or service? Or should xstate's action send a message to the tcp node, and then the tcp node updates the status of the xstate node after processing?

For this, I also modified the official tcp request node a bit: [https://github.com/zhangmx/node-red-contrib-tcp-request2](https://github.com/zhangmx/node-red-contrib-tcp-request2)，add timeout and retry feature.This eliminates the need to 'control' the timeout and retry states

Thank you very much for giving me some guidance and advice if it is convenient for you～

**Pull request closed without merging**
